import Head from 'next/head';
import {
  Skeleton,
  SkeletonCircle,
  SkeletonText,
  Divider,
  Flex,
} from '@chakra-ui/react';
import Header from 'shared/header/header';
import BannerCarousel from 'modules/banner-carousel/banner-carousel';
import TopUp from 'modules/top-up/top-up';
import Products from 'modules/products/products';
import ShopRegistration from 'modules/shop-registration/shop-registration';
import Footer from 'shared/footer/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        <div style={{ marginBottom: '40px' }}>
          <BannerCarousel />
        </div>

        <TopUp />

        <Divider margin="30px auto" />
        <Products />
        <ShopRegistration />
      </div>
     
      <Footer/>
    </>
  );
}
